language: python
python:
  - 3.5
  - 3.6
env:
  - WITH_MPI=no
  - WITH_MPI=yes
install:
  - sudo apt-get update
  - if [ "$WITH_MPI" == "yes" ]; then sudo apt-get install openmpi-bin libopenmpi-dev; fi
  - python -m pip install --upgrade -r requirements.txt
  - python setup.py install
  - if [ "$WITH_MPI" == "yes" ]; then python -m pip install --no-binary mpi4py mpi4py==${MPI4PY_VERSION}; fi
script:
  - if [ "$WITH_MPI" == "yes" ]; then python run-tests.py --verbose --full-trace -s; else pytest --verbose --full-trace -s; fi
notifications:
  email:
    - antoine.sanner@imtek.uni-freiburg.de
    - lars.pastewka@imtek.uni-freiburg.de
