language: python
matrix:
  include:
  - env: WITH_MPI=no
    python: 3.4
  - env: WITH_MPI=yes
    python: 3.4
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy
  - source activate test-environment
  - python -m pip install -r requirements.txt
  - python setup.py install
script:
  - "pytest"
  - 'if [ "$WITH_MPI" == "yes" ]; then python run-tests.py; fi'
notifications:
  email:
    - antoine.sanner@imtek.uni-freiburg.de
    - lars.pastewka@imtek.uni-freiburg.de
