language: generic
matrix:
  include:
  - env: WITH_MPI=no
    os: linux
    dist: xenial
  - env: WITH_MPI=yes
    os: linux
    dist: xenial
before_install:
  - source .travis.before_install.bash
install:
  - "python setup.py install"
script:
  - "pytest"
  - 'if [ "$WITH_MPI" == "yes" ]; then python run-tests.py; fi'
notifications:
  email:
    - antoine.sanner@imtek.uni-freiburg.de
    - lars.pastewka@imtek.uni-freiburg.de
